sonar.projectKey=jbfishnet_modbusscanner
sonar.projectName=modbusscanner
sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/testserver/**,**/*.db,**/integration-test.js,**/tests.js